### ISSUE TITLE
bad typedef

### ISSUE THREAD

**Issue by tzimiskes** [danzimm/frak#1]
https://github.com/danzimm/frak/blob/b0aff27a092939d5ead9e004ffbf9d4d3ca48c56/frak_args.h#L14

reserved by POSIX

**Comment by danzimm** [comment]
This is technically true, thanks for pointing it out!

Similar to some of the folks on [this SO](https://stackoverflow.com/questions/29099325/standard-alternative-to-posix-typedef) I’m keen on using this practice uniformly throughout frak. In particular frak-defined structures can optionally have a typedef of a pointer to themselves, named the same, but with _t appended.
